# Generated by Django 2.2.1 on 2019-06-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=2, upload_to='avatar/'),
            preserve_default=False,
        ),
    ]
