# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190606_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='empty.png', upload_to='avatar/'),
        ),
    ]
